###
POST http://localhost:5039/api/server/signup
Accept: application/json
Content-Type: application/json

{
    "Username": "User123abc",
    "Password": "Password123@",
    "Email": "brannd101@gmail.com"
}

###

POST http://localhost:5039/api/server/login
Accept: application/json
Content-Type: application/json

{
    "Username": "User123abc",
    "Password": "Password123@"
}

###
POST http://localhost:5039/api/server/emailverify 
Accept: application/json
Content-Type: application/json

{
    "Email": "brannd102@gmail.com"
}